### ISSUE TITLE
Awesome work! How to change the hits text?

### ISSUE THREAD

**Issue by jinfagang** [gjbae1212/hit-counter#1]
Hi!! How to changes the hits text of svg? Any way?

**Comment by gjbae1212** [comment]
It is not yet a plan. 
I would say it is a sound good which changes a title when exists a query string param(title).
I will be getting to start this issue as soon. 
thank you.

**Comment by jinfagang** [comment]
@gjbae1212  Really hoping for that!

**Comment by gjbae1212** [comment]
@jinfagang 
It's modified this issue. Hits Text is possible to change.
If you'd like to change text, adding `title` query parameter.
```
EX) https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=your-url&title=your-title	
```
