### ISSUE TITLE
Issue with cookies

### ISSUE THREAD

**Issue by GitBoudewijn** [gjbae1212/hit-counter#20]
Hey,

Google Chrome is blocking the cookies from the counter.

This is what it says in the console:
_A cookie associated with a cross-site resource at http://hits.seeyoufarm.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032._

**Comment by gjbae1212** [comment]
@GitBoudewijn 
Thank you. 
I have applied it.
